---
- name: CentOS7 or EL 7 specific code
  include: centos7.yml
  when: (ansible_distribution == "CentOS"  and ansible_distribution_major_version > '6') or (ansible_distribution == "MostlyLinux"  and ansible_distribution_major_version > '6') or (ansible_distribution == "RedHat"  and ansible_distribution_major_version > '6')
- name: Ubuntu | Debian
  include: ubuntu.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
